### ISSUE TITLE
dangling symlink = panic

### ISSUE THREAD

**Issue by naknak-** [the8472/ffcnt#3]
$ ln -s /nonexistent/path dangle
$ ffcnt  -s
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Aborted

**Comment by the8472** [comment]
should be fixed with 909b76a37a3a8c5a7e40871e1e835e65ead5b170

**Comment by naknak-** [comment]
thanks!
